title: 'Minimaxing by HTML5 UP'
heading: Minimaxing
author:
  name: Hugh Barnes
  # email: 'joe@test.com'
metadata:
    description: 'Port of HTML5UP Minimaxing theme to Grav content management system.'

